export enum ContractRequestStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    LESSOR_ACCEPTED = "LESSOR_ACCEPTED",
    AGENT_ACCEPTED = "AGENT_ACCEPTED",
    ALL_ACCEPTED = "ALL_ACCEPTED",
    REJECTED = "REJECTED",
}