export enum ContractStatus {
    PENDING = "PENDING",               // 블록체인 전송 준비됨
    REQUESTED = "REQUESTED",           // 블록체인에 생성 요청 보냄
    DOWN_PAYMENT_PENDING = "DOWN_PAYMENT_PENDING",
    DOWN_PAYMENT_PAID = "DOWN_PAYMENT_PAID",
    BALANCE_PAYMENT_PENDING = "BALANCE_PAYMENT_PENDING",
    BALANCE_PAYMENT_PAID = "BALANCE_PAYMENT_PAID",
    DEPOSIT_RETURNED = "DEPOSIT_RETURNED",
    TERMINATED = "TERMINATED"
}
