export enum NotificationType {
    CONTRACT_REQUEST = "CONTRACT_REQUEST",           // 계약 요청
    CONTRACT_CREATION_REQUEST = "CONTRACT_CREATION_REQUEST", // 계약서 작성 요청
    CONTRACT_CREATION_READY = "CONTRACT_CREATION_READY", // 계약서 작성 완료
}